
export const SET_ALL_USER='SET_ALL_USER';

export const SET_CURRENT_USER='SET_CURRENT_USER';

export const SET_ALL_USER_FOLLOWERS='SET_ALL_USER_FOLLOWERS';

export const SET_CURRENT_USER_FOLLOWERS='SET_CURRENT_USER_FOLLOWERS';

export const SET_ALL_FOLLOWER_REPOS='SET_ALL_FOLLOWER_REPOS';

export const SET_CURRENT_FOLLOWER_REPOS='SET_CURRENT_FOLLOWER_REPOS';
